### ISSUE TITLE
MOBILE: Formating on the contact us page

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#10]
![IMG_4841 (1)](https://github.com/philhancox/openhousepictures/assets/144906896/75a605e6-ce34-447b-96ea-e57fc0c9af56)

Text/bars are too close to the edge.

**Comment by philhancox** [comment]
Resolved; spacing added on mobile resolution.

![Screenshot_20230913-195502](https://github.com/philhancox/openhousepictures/assets/12893491/b76bcf61-09dd-4aa3-bce3-3f98e591a657)
