### ISSUE TITLE
MOBILE: GENERAL - Slow loading vimeo links

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#12]
![IMG_4844](https://github.com/philhancox/openhousepictures/assets/144906896/997c036a-4e10-485f-ac6b-593502c17aaa)

From TV commercial page.

![IMG_4848](https://github.com/philhancox/openhousepictures/assets/144906896/7ac2848d-2789-4a87-a9ef-f59978cb204d)

From corporate video production.

**Comment by philhancox** [comment]
There's not much we can do our end about Vimeo download speeds, especially on mobile where it would naturally be slower. Making the experience a little better for users while they're waiting, such as placeholders, sending priority signals to Vimeo etc is a lot of work in return for dealing with a short lag which is to be expected on mobile sites.
