### ISSUE TITLE
MOBILE: ABOUT US PAGE - Formatting issues.

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#13]
https://github.com/philhancox/openhousepictures/assets/144906896/a5ba4b9b-0b59-490b-9314-85dd3ef79bd3

**Comment by philhancox** [comment]
Cleaned up spacing issues as they were necessary for desktop but not for mobile, that's been sorted out.
Anything else may require more specific notes; mobile design can be discussed with Brad if changes are wanted.
