### ISSUE TITLE
MOBILE: OUR SERVICES PAGE - Image on training videos didn't load / Enquire about video production services today and logos part vanishes on the services page

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#14]
![IMG_4845](https://github.com/philhancox/openhousepictures/assets/144906896/a15ca62c-6c51-4895-95c8-c2ddfe8a2567)
![IMG_4847](https://github.com/philhancox/openhousepictures/assets/144906896/0bccfef2-89f3-4b8b-8dc2-d3c7e300cd37)

**Comment by philhancox** [comment]
Can not replicate with multiple attempts; it sounds like a connection issue. The blue bar suggests the connection hasn't completed, so any elements not yet loaded will not appear on the page - this is true of any website.
