### ISSUE TITLE
PC: Navigation bar glitches out when it first takes you to the website

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#3]
![image](https://github.com/philhancox/openhousepictures/assets/144906896/1bc3bbf8-7c2c-4d15-abe6-839e497b9e6a)

**Comment by philhancox** [comment]
The website is loading scripts, checking device, viewports etc and building the webpage, it's just the menu is a more complex thing to build than some other parts of the page and indeed, it can look like a glitch until it's snapped into place. 
I've written some code that ensures this transition is much, much faster and thus snaps the menu into place almost immediately on first page load which gets even faster on additional page visits.
