### ISSUE TITLE
MOBILE: Menu bar has all pages open instead of drop down bars

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#7]
![IMG_3307](https://github.com/philhancox/openhousepictures/assets/144906896/7b44eb30-96e2-4b52-9c9d-7694ce86a317)

**Comment by philhancox** [comment]
This is part of the foundation theme and the plugins/code etc they use to build the menu on desktop and mobile. As the menu employs a hover dropdown on desktop, but doesn't have hover on mobile, they have made the decision to have mobile menus always open. This wasn't known when we selected the foundation, but even so, it's not a bug and it's not uncommon.
If this is a must-fix, it would require significant work to either attempt to override the foundation code or employ a new menu system.
